[theme]
base = "dark"
primaryColor = "#e06c75"
backgroundColor = "#111111"
secondaryBackgroundColor = "#1e2228"
textColor = "#9cdef2"
font = "monospace"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
