[theme]
base = "light"
primaryColor = "#24649a"
backgroundColor = "#f7f5ef"
secondaryBackgroundColor = "#eeece5"
textColor = "#202e3d"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
